server:
  applicationConnectors:
    - type: http
      port: 8080

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    com.bloom.bloom: DEBUG

defaultName: friend